### ISSUE TITLE
Examples from ant.apache.org for directory matching

### ISSUE THREAD

**Issue by jeroenheijmans** [WichardRiezebos/ant-path-matching#1]
Heya, I was checking out the library, and installed version 1.0.10 from NuGet, ran some tests against it to see if it's consistent with the [docs on the apache site](http://ant.apache.org/manual/dirtasks.html#patterns) (though I'm not sure if it's the intention to be compatabile with those _directory_ patterns?), and found that in some cases the results are different. 

Here's the full set of tests representing the examples from aforementioned site:

```csharp
[Description("See also http://ant.apache.org/manual/dirtasks.html#patterns")]
// CVS Examples
[TestCase("**/CVS/*", "CVS/Repository", true)]
[TestCase("**/CVS/*", "org/apache/CVS/Entries", true)]
[TestCase("**/CVS/*", "org/apache/jakarta/tools/ant/CVS/Entries", true)]
[TestCase("**/CVS/*", " org/apache/CVS/foo/bar/Entries", false)]
// Jakarta examples
[TestCase("org/apache/jakarta/**", "org/apache/jakarta/tools/ant/docs/index.html", true)]
[TestCase("org/apache/jakarta/**", "org/apache/jakarta/test.xml", true)]
[TestCase("org/apache/jakarta/**", "org/apache/xyz.java", false)]
// CVS with prefix path examples
[TestCase("org/apache/**/CVS/*", "org/apache/CVS/Entries", true)]
[TestCase("org/apache/**/CVS/*", "org/apache/jakarta/tools/ant/CVS/Entries", true)]
[TestCase("org/apache/**/CVS/*", "org/apache/CVS/foo/bar/Entries", false)]
// Test examples
[TestCase("**/test/**", "test", true)]
[TestCase("**/test/**", "test.png", true)]
[TestCase("**/test/**", "some/test/file.png", true)]
public void Matcher_WhenGivenExamplesFromApacheDocs_ReturnsExpected(
    string pattern,
    string input,
    bool shouldMatch)
{
    var matcher = new AntPathMatching.Ant(pattern);
    var result = matcher.IsMatch(input);
    Assert.That(result, Is.EqualTo(shouldMatch));
}
```

Some cases give an unexpected result, i.e. these:

- `[TestCase("**/CVS/*", "CVS/Repository", true)]`
- `[TestCase("org/apache/**/CVS/*", "org/apache/CVS/Entries", true)]`
- `[TestCase("**/test/**", "test", true)]`
- `[TestCase("**/test/**", "test.png", true)]`

Are those expected to work? Or should I only be testing files, not directory paths? Or am I missing something?

**Comment by WichardRiezebos** [comment]
Yes, it was intended to match the apache's docs. I will add your test-cases. I will look into the unexpected results.

Thanks for the feedback!
