### ISSUE TITLE
Ignore case on file pattern matching 

### ISSUE THREAD

**Issue by borismod** [WichardRiezebos/ant-path-matching#7]
Ignore case in pattern when searching for files.

Assume that there is a directory with files:
c:\dirname\file1.txt

```
            var ant = new Ant("c:\DirName\*.*");
            var antDirectory = new AntDirectory(ant);
            var files = antDirectory.SearchRecursively(@"c:\");
```
files should contain the file1.txt, but it's empty

**Comment by WichardRiezebos** [comment]
No it should not, since the pattern is case-sensitive and will never match `DirName` with `dirname`.
